### PR TITLE
Spree from the trenches

### PR DESCRIPTION
**Pull request by peterberkenbosch**
Talk about implementing a SpreeCommerce web-shop.

### CODE REVIEW

**Comment by johanb** [comment]
:+1: I'm really looking forward to this!

argh.. to late

**Comment by peterberkenbosch** [comment]
I was kinda stupid.. and did not noticed the deadline for submitting was March 30th.. so this one will definitely not be at Euruko.. :P

**Comment by johanb** [comment]
There is always [SpreeConf EU](http://spreeconf.com/)

**Comment by dhiemstra** [comment]
Hey Peter,
Thanks for the talk proposal for EuRuKo 2012.
We are sorry but your proposal was submitted passed the deadline, and to be fair to others who submitted their proposals on time we won't be able to accept it.
None the less we hope to see you at EuRuKo this year!

**Comment by peterberkenbosch** [comment]
Yeah.. I noticed it like 5 sec. after the pull request :) thanks for your message though! 

Peter Berkenbosch
--------—-------—---------—
Wat niet kan, is nog nooit gebeurd.
-------—--------—-----------—
Verstuurd vanaf mijn iPhone.

**Pull request closed without merging**
