### PR TITLE
Backbone.js – Clientside MVC

### PR DESCRIPTION
**Pull request by markbates**
We all want our applications to be faster and more responsive. We can do that with caching, faster database servers, etc… but we can also do that by writing more responsive front-end code.

Do we really need to go back to the server to re-render a page if someone adds a new comment? Or edits some text? Or uploads a new photo? Of course not. 

In the past writing these sorts of responsive front-ends would result in a mess of jQuery or MooTools code that was held together with chewing gum and luck. Now there’s Backbone.js

Backbone.js is a powerful JavaScript model, view, and controller framework. 

In this talk we’ll look at how to get Backbone.js up and running and we’ll quickly build the canonical Todo application. We’ll learn about Backbone models, views, and routers.

You’ll be surprised at how quickly you can write the most responsive applications you’ve ever written, and how well organized and clean your code will be.

### CODE REVIEW

**Comment by stecb** [comment]
Hey! 2 things:
- the `C` on backbone is for `collections`, controller is something 'inside' the view part :)
- MooTools, has - as you probably already know - a completely different approach compared to jQuery. It leads the developer (who knows how it **really** works) to write clean and modularized code and therefore the risk of a mess is limited and in general less than using jQuery (IMO). Btw, I see that development of single page apps requires a good 'structure' support framework.

p.s. I really like backbone, its concept, and how much it helps the development of single page apps. On the other side, on 'regular' web apps (multiple pages, not-that-heavy js based) it shouldn't be used. Or it could be used in the right way and not abused :)

**Comment by DouweM** [comment]
:+1:

**Comment by johanb** [comment]
:+1:

**Comment by mackuba** [comment]
I love Backbone, I'm using it in my current project, but I'm not sure if this isn't too far from Ruby for a Ruby conference...

**Comment by mitch000001** [comment]
+1

**Comment by knaveofdiamonds** [comment]
-1

I'm interested in backbone, but not at euruko.

**Comment by lesniakania** [comment]
+1

**Pull request closed without merging**
