### PR TITLE
Modular & reusable front-end code with HTML5, Sass and CoffeeScript

### PR DESCRIPTION
**Pull request by roytomeij**

### CODE REVIEW

**Comment by ghost** [comment]
I would love to have this talk in the schedule :)

**Comment by DouweM** [comment]
:+1:

**Comment by roytomeij** [comment]
Get ready for some shameless self promotion. I performed this talk at [wroc_love.rb](http://wrocloverb.com/) yesterday, and here's what people had to say about it: http://storify.com/roy/some-tweets-about-my-wrocloverb-talk

**Comment by johanb** [comment]
:+1:

**Comment by steveklabnik** [comment]
This talk was great at wroc_love.rb

**Comment by lukaszsagol** [comment]
:+1: You can't go wrong with Bob Ross images and the same goes for @roytomeij's talk.

**Comment by daxhuiberts** [comment]
Bob Ross on an afro unicorn! :+1:

**Comment by saturnflyer** [comment]
:+1: a @roytomeij presentation is a fun and educational presentation

**Comment by leifbladt** [comment]
:+1:

**Comment by chastell** [comment]
+1: one of my top three talks at wroc_love.rb (the other two being @steveklabnik’s and @DrummerHead’s)!

**Comment by seancribbs** [comment]
:+1:

**Comment by mediafinger** [comment]
:+1: Interesting topic AND good speaker?! Perfect!

**Comment by LevelbossMike** [comment]
:+1:

**Comment by mordaroso** [comment]
:+1:

**Comment by fidel** [comment]
+1

**Comment by hugoestr** [comment]
+1

**Comment by peterberkenbosch** [comment]
+1

**Comment by agatkamazur** [comment]
+1! I missed your talk on wroclove.rb, would love to hear this one!

**Comment by warrenv** [comment]
+1
Nice talk, saw it at ruby nation. and it's got Bob Ross in it!

**Comment by scottdavis** [comment]
+1 for Bob Ross

**Comment by roytomeij** [comment]
Bragging time: Scott, of the Compass core team, endorses this talk. And Bob Ross. Just sayin'.

**Comment by scottdavis** [comment]
@roytomeij it will cost you 5$ for using my name

**Comment by roytomeij** [comment]
@scottdavis, I'll buy you a round next time.

**Comment by campbell** [comment]
+1

**Comment by chirul0** [comment]
Loved @roytomeij's talk @RubyNation!  Go see it live!

**Comment by grayherter** [comment]
@roytomeij from the perspective of one of the RubyNation organizers, Roy was perfect for us, a great presentation and an engaged conference attendee. People loved him over here. Do yourselves a favor and work him into your schedule.

**Comment by roytomeij** [comment]
Video for this talk (the 30-minute version): http://www.youtube.com/watch?v=T6-75HdADc8

**Comment by Juice10** [comment]
Checked out the video, pretty cool talk. Liked it allot

**Pull request closed without merging**
