### PR TITLE
Cucumber: The Right Way - Better acceptance testing

### PR DESCRIPTION
**Pull request by zsiec**
Cucumber is a useful tool that is often used incorrectly. Many people abandon it altogether without understanding its true potential. Whether you are working for a client or on an internal product, clear and concise tests will reduce confusion and ensure you stay on the right track with your development. In this talk, we will explore what should and should not be a 'step'. We'll also look at how to properly test your front end javascript and the gotchas surrounding headless browsers. We will see how easy it is to test external APIs in isolation with VCR, and more. The acceptance tests we write can do so much more than test our code. We will examine how cucumber will make communication with your stakeholder smoother, help you brainstorm more effectively, and give you excellent project visibility.

### CODE REVIEW

**Comment by rmcastil** [comment]
:+1:

**Comment by brennandunn** [comment]
I would buy a :beer: for you whilst in Amsterdam to see presented.

**Comment by ugisozols** [comment]
:+1:

**Comment by DouweM** [comment]
:+1:

**Comment by s2k** [comment]
+1

**Comment by mediafinger** [comment]
I'll call it Cucumbersome... but most probably I could learn something from that talk.

**Comment by yundt** [comment]
+1

**Comment by osegrums** [comment]
+1

**Pull request closed without merging**
