### PR TITLE
Corporate invaders: Building an “Operating System” for the Enterprise with Ruby

### PR DESCRIPTION
**Pull request by myabc**
Joint talk by Pedro Visintin (@peterpunk) and Alex Coles (@myabc)

No. Not Corporate Raiders. Gordon Gekko stays at the door.

Is this you?
- You need to develop a system that automates large parts of your business. Be it selling airline tickets or books.
- You want a system that lets you manage (and evolve) your business processes as easily as UNIX processes, but don't want to write a check to Big Blue.
- You hate the words Corporate and Enterprise, but love working on big, ambitious and technically demanding projects.
- You want to use Ruby.

Based on our personal experiences building a platform for prepaid credit cards, we'll be taking a tour of the components you need to build the perfect “Corporate OS”.

### CODE REVIEW

**Comment by pietia** [comment]
+1 (pierwszy!)

**Comment by nicops** [comment]
+1! I want to see this

**Comment by myabc** [comment]
@pietia thanks!!

**Comment by wordgraphy** [comment]
+1 @wordgraphy

**Comment by hrbg** [comment]
+1 If Gordon Gekko stays at the door

**Comment by purbon** [comment]
+1 @purbon

**Comment by shingara** [comment]
:+1:

**Comment by osegrums** [comment]
+1

**Comment by DouweM** [comment]
+1

**Comment by solnic** [comment]
awesome! :+1:

**Comment by bumi** [comment]
+1

**Comment by jmettraux** [comment]
+1

**Comment by kedarmhaswade** [comment]
+1

**Comment by arvicco** [comment]
+1

**Comment by marsbomber** [comment]
+1

**Comment by damontorgerson** [comment]
+1

**Comment by dbussink** [comment]
+1

**Comment by jmrepetti** [comment]
+1 !

**Comment by tosch** [comment]
+1

**Comment by knewter** [comment]
+1

**Pull request closed without merging**
