### PR TITLE
Proposal: Lean DDD for hackers

### PR DESCRIPTION
**Pull request by nu7hatch**
What happens when Lean Startup meets Domain Driven Development? Do you think it may become a love story with a happy ending? Most of us hackers know that while working for clients we have to get things done, but very few of us know that we should also wisely choose what things to do. That we should eliminate waste from our design, architecture and code. This talk will attempt to present important business-related stuff and its influence on our code from the perspective of an uber geek and hacker.

### CODE REVIEW

**Comment by dcadenas** [comment]
+1

**Comment by danishkhan** [comment]
It's always difficult I've notice to combine business logic with code. I would love to hear a talk about this. +1

**Comment by bjensen** [comment]
+1

**Comment by yaph** [comment]
+1

**Comment by picandocodigo** [comment]
+1

**Comment by elcuervo** [comment]
+1 OMG DDD FTW.

**Comment by foca** [comment]
+1!

**Comment by arvenil** [comment]
+1

**Comment by osegrums** [comment]
+1

**Comment by severin** [comment]
+1

**Pull request closed without merging**
