### PR TITLE
rvm talk proposal

### PR DESCRIPTION
**Pull request by mpapis**
# RVM

RVM is a tool of most ruby or rails developers, it is hard to imagine workflow without it.
There are few other tools like rbenv or rbfu but RVM as the first one got a good start an wide adoption.

Most developers use RVM in very limited scope not knowing about useful functionalities.
I would like to show more about RVM, all the cool features it has but are rarely used.

RVM is evolving, some of the old features got deprecated or even replaced with new ones.
We are continuously adding new features and fixing old ones - I want to show the most useful ones.

There was a lot of confusion whether RVM should be used in production, 
I would like to show how to work with RVM on production and how simple it can be.

Hope fully there will be few minutes left to answer questions from the audience.

### CODE REVIEW

**Comment by remear** [comment]
Will this conference talk go over JewelryBox?

**Comment by mpapis** [comment]
It will at least mention JB & RIX, detail level depends on the time.

**Comment by DouweM** [comment]
:+1:

**Comment by gokulnath** [comment]
:+1:

**Pull request closed without merging**
