### PR TITLE
Designing Hypermedia APIs

### PR DESCRIPTION
**Pull request by steveklabnik**
I've been yelling at everyone about how they don't do REST right, now it's time to show them how!

### CODE REVIEW

**Comment by joshk** [comment]
Oh Steve Steve Steve, why did you delete the example? others may need it! ;)

**Comment by steveklabnik** [comment]
:D

**Comment by rkh** [comment]
:+1:

**Comment by DouweM** [comment]
:+1:

**Comment by steveklabnik** [comment]
:D

I should add the slides from when I gave it previously are here: http://github.com/steveklabnik/hypermedia-presentation though I change them each time I give the talk.

**Comment by rodzyn** [comment]
+1

**Comment by ghost** [comment]
:+1:

**Comment by johanb** [comment]
:+1:

**Comment by mcollina** [comment]
:+1:

**Comment by Stanley** [comment]
:+1:

**Comment by roytomeij** [comment]
:+1:

I know shit about Ruby, but the audience at the wroc_love.rb conference enjoyed @steveklabnik's talk, so it must have been amazing. And he's a fun guy (although getting him through airport security will be a bitch).

**Comment by saturnflyer** [comment]
:+1: if we're going to try REST, we should do it right.

**Comment by lucaspinto** [comment]
+1

**Comment by chastell** [comment]
+1: one of my top three talks at wroc_love.rb (the other two being @roytomeij’s and @DrummerHead’s)!

**Comment by tlossen** [comment]
+1

i agree, one of the best (and most controversial) presentations at wroc_love.rb

**Comment by mediafinger** [comment]
:+1: Sounds like fun!

**Comment by moonglum** [comment]
:+1: About time to!

**Comment by ayosec** [comment]
+1

**Comment by mitch000001** [comment]
+1

**Comment by despo** [comment]
+1

**Comment by osegrums** [comment]
+1

**Comment by nu7hatch** [comment]
+1

**Pull request closed without merging**
