### PR TITLE
My Server for Aiur: How Starcraft Taught Me To Scale

### PR DESCRIPTION
**Pull request by schneems**
All the Starcraft n00bs know just what to do. They take all the resources they can, and upgrade all the expensive tech and think to themselves, "soon i'll be unstoppable". Unfortunately "eventually unstoppable" is the same as dead right now. Premature optimization and abstraction can kill a business faster than not being able to scale. In this talk we'll take a look at how to pick the right unit composition (databases vs. NoSQL), balance your macro and micro (scale out vs. up), and choose the right race (programing language). If you've never played Starcraft, and can't tell a ultralisk from a firebat, don't worry there's still a room for you. Sorry, no Zerg allowed.
## Bio

Richard was a Platinum 1v1 Random Starcraft 2 player, before he decided to resume seeing daylight. He now works for Heroku helping to scale millions of applications. He loves developing in Ruby and collecting vespene gas. When he's not at work he teaches Rails at the University of Texas and enjoys snowboarding.

### CODE REVIEW

**Comment by mackuba** [comment]
I so want to see this. En Taro Adun!

**Comment by rubyku** [comment]
+1!

**Comment by psyho** [comment]
+1

**Comment by kronn** [comment]
+1

**Comment by MoritzBecker** [comment]
+1

**Comment by tlossen** [comment]
+1

sounds fun, though i never played starcraft.

**Comment by schneems** [comment]
@tlossen I'm writing the talk where starcraft references are there to keep the audience engaged, there's still plenty to be learned. promise.

**Comment by Narnach** [comment]
+1, though not sure if it still helps to get picked :)

**Comment by severin** [comment]
+1

**Pull request closed without merging**
