### PR TITLE
Testing your JavaScript with Jasmine

### PR DESCRIPTION
**Pull request by markbates**
As Ruby/Rails developers we love to test our applications, we thrive on seeing those green dots and 100% test coverage of our Ruby code, but how well tested is your JavaScript or CoffeeScript code? I have a feeling that the answer to that question is a sheepish green and rosy cheeks. Well, let's change that!

Let's spend some time seeing how easy it can be to set up Jasmine, a RSpec-like testing framework for JavaScript/CoffeeScript, in your Ruby/Rails application. We'll learn how to test that our jQuery or Backbone code is doing what it supposed to. It's really not as hard as you think it might be.

By the end of this talk you should no longer fear testing your JavaScript. You will embrace it. It'll mean more of those green dots and true 100% test coverage!

### CODE REVIEW

**Comment by stecb** [comment]
+1

**Comment by joshk** [comment]
Side note, you don't need to remove the example directory, others might need it :)

**Comment by markbates** [comment]
Oops. My bad. :)

**Comment by markbates** [comment]
I can fix it.

**Comment by markbates** [comment]
All fixed.

**Comment by DouweM** [comment]
:+1:

**Comment by driv3r** [comment]
:+1:

**Comment by 5v3n** [comment]
:+1:

**Comment by mediafinger** [comment]
:+1: (Huh - JavaScript can be tested?!  ;-))

**Comment by LevelbossMike** [comment]
:+1:

**Comment by lesniakania** [comment]
+1

**Comment by dmasur** [comment]
+1

**Pull request closed without merging**
