### PR TITLE
The Future is Dead: Long live the Past

### PR DESCRIPTION
**Pull request by elcuervo**
We keep looking for good ideas to improve our code, to make our systems even more powerful. But there are a lot of good ol' ideas that we are discovering but most of them were already thought about years ago.

I propose a journey through technology archeology to re-discover all that tools that are burien deep into the internetz.

Remember the scriptures of 'The unix way', the HTTP reference engraved in stone and learn from the elders about concurrency and single responsability.

### CODE REVIEW

**Comment by nu7hatch** [comment]
Yay! +1

**Comment by foca** [comment]
+1!

**Comment by dcadenas** [comment]
+1

**Comment by fbrubacher** [comment]
+1 !

**Comment by DrummerHead** [comment]
+1
http://mcdlr.com/i/succeed.jpg

**Comment by gorenje** [comment]
+1

**Comment by tizoc** [comment]
+1

**Pull request closed without merging**
