### PR TITLE
Your infrastructure is obsolete, deprecate it!

### PR DESCRIPTION
**Pull request by calavera**
At Engine Yard, we run thousands of virtual machines for our clients, but the services that we designed years ago to provision those VMs and give service to our customers has become obsolete.

This talk is about how we're deprecating these services without forcing our customers to move forward neither abandon us. We'll talk about software as a service to provision big cloud infrastructures, and how our underlying services configure instances for users running bleeding edge Ruby technologies, without abandoning customers that still use Ruby1.8.6+mongrel. We'll talk about Chef, how to use it efficiently and also how to get that nobody in your team want to use it anymore. But most important, we'll talk about customers' happiness and how it's hidden behind a simple mouse click.

### CODE REVIEW

**Comment by juliancheal** [comment]
+1

**Comment by joshk** [comment]
Hey @calavera 

Can you please fix your PR by not over-writing the example proposal but creating a new directory for your talk like the repo readme asks you too.

Also, please include a profile pic if you have one :)

Thanks,

Josh

**Comment by calavera** [comment]
sure thing!!!

**Comment by ghost** [comment]
:+1:

**Comment by mpapis** [comment]
:+1:

**Comment by hemju** [comment]
:+1:

**Comment by rodreegez** [comment]
+1

**Comment by LevelbossMike** [comment]
+1

**Pull request closed without merging**
