### PR TITLE
A Case of Accidental Concurrency

### PR DESCRIPTION
**Pull request by seancribbs**
Re-entrancy, the silent killer.

### CODE REVIEW

**Comment by pzol** [comment]
+1

**Comment by flippingbits** [comment]
+1

**Comment by tlossen** [comment]
+1

(sean, why don't you swap the tltle and subtitle? would be even more catchy, i think.)

**Comment by josephwilk** [comment]
+1

**Comment by seancribbs** [comment]
_waves to @josephwilk_

**Comment by elisehuard** [comment]
+1

**Comment by mostlyobvious** [comment]
+1

**Comment by mackuba** [comment]
+1

**Comment by mitch000001** [comment]
+1

**Comment by myabc** [comment]
+1

**Pull request closed without merging**
