### PR TITLE
Proposal 2: Someone is Wrong

### PR DESCRIPTION
**Pull request by josephwilk**
Rhetoric for programmers

### CODE REVIEW

**Comment by ghost** [comment]
double :+1: for Someone is Wrong!

**Comment by tlossen** [comment]
+1 for "someone is wrong"

bonus points for the xkcd reference: http://xkcd.com/386/

**Comment by martinrehfeld** [comment]
+1

would love to hear "someone is wrong"

**Comment by mediafinger** [comment]
:+1: Joseph is a good speaker and this topic seems to be a great supplement to all those tech talks.

**Comment by elisehuard** [comment]
:+1:

**Comment by knaveofdiamonds** [comment]
+1

**Comment by kronn** [comment]
:+1: for "Someone is wrong"

**Pull request closed without merging**
