### PR TITLE
`bundle install` - y u so slow

### PR DESCRIPTION
**Pull request by hone**
This talk tells the shortcomings of Bundler 1.0 and how Bundler 1.1 increases developer happiness. This includes the story of working with the gemcutter team to add an API to rubygems.org and building support to make bundle install significantly faster in 1.1. Finally, the talk will conclude with plans for the future in Bundler 1.2 and beyond to further make application development easier.

People will walk away with a better understanding of how bundler works and features to help ease app development pain while using it.

### CODE REVIEW

**Comment by daneharrigan** [comment]
+1

**Comment by schneems** [comment]
+1

**Comment by raulb** [comment]
+1

**Comment by raul** [comment]
+1

**Comment by mackuba** [comment]
+1, Bundler definitely gets way more negative feelings than it deserves, this talk might help a bit with that.

**Comment by DouweM** [comment]
+1

**Comment by glenngillen** [comment]
+1

**Pull request merged**
