### PR TITLE
Ruby: You've Changed, Bro

### PR DESCRIPTION
**Pull request by holman**
Hey here's a talk.

### CODE REVIEW

**Comment by DouweM** [comment]
:+1:

**Comment by lucaspinto** [comment]
+1

**Comment by Stanley** [comment]
:+1:

**Comment by vmg** [comment]
-1000 holman is banned from Europe. Gonna talk with the govt about this.

**Comment by DouweM** [comment]
@tanoku What?

**Comment by holman** [comment]
Vicent is just :trollface:ing around. He actually can't possibly wait to see my talk.

**Comment by DouweM** [comment]
Ah! It's 4 AM here, so my :trollface:-detector isn't working optimally.

**Comment by ghost** [comment]
:+1:

**Comment by josephwilk** [comment]
+1

**Comment by awendt** [comment]
+1

**Comment by mediafinger** [comment]
:+1: As your talks are usually entertaining, the subject doesn't matter that much ;-)

**Comment by rodreegez** [comment]
+1 for mild hilarity.

**Comment by LevelbossMike** [comment]
+1

**Comment by moonglum** [comment]
Looking forward to it!! :+1:

**Comment by johanb** [comment]
:+1:

**Comment by mackuba** [comment]
:+1:

**Comment by rkh** [comment]
:+1:

**Comment by danishkhan** [comment]
@holman I only +1 this on the assumption that you will have a mustache for this talk.

**Comment by mitch000001** [comment]
+1

**Comment by kronn** [comment]
:+1:

**Comment by colszowka** [comment]
_edit: I'm stupid_

**Comment by colszowka** [comment]
Whoops, sorry. I'm obviously too stupid to tell a pull request description from the actual commit. Thanks for the proposal & +1 :blush:

**Comment by juliancheal** [comment]
+1

**Comment by osegrums** [comment]
+1

**Pull request closed without merging**
