### PR TITLE
My two talk proposals.

### PR DESCRIPTION
**Pull request by josephwilk**

### CODE REVIEW

**Comment by rkh** [comment]
Now they have to either accept none or both! Oh no! :D

**Comment by rkh** [comment]
Also, I want both talks in, so this is fine.

**Comment by joshk** [comment]
small note : can you undo deleting the example proposal :)

**Comment by josephwilk** [comment]
:) Woops did not think of that!

**Comment by josephwilk** [comment]
Thats what I get for trying to do something having not slept since Saturday. I'll delete this and try again.

**Comment by joshk** [comment]
hahaha :heart::heart::heart:

**Pull request closed without merging**
