### PR TITLE
Of Remote Islands, Monsters, and Polyglot Knights 

### PR DESCRIPTION
**Pull request by phuesler**
Developing multi player mobile games has many stories, this is one of it

### CODE REVIEW

**Comment by guillermo** [comment]
Nice +1

**Comment by jkischkel** [comment]
+1

**Comment by tlossen** [comment]
+1

yay for "polyglot knights"!

**Comment by josephwilk** [comment]
+1

**Comment by martinrehfeld** [comment]
+1

bring on them monsters!

**Pull request closed without merging**
