### PR TITLE
ZeroMQ: Supercharged Sockets by @technoweenie

### PR DESCRIPTION
**Pull request by technoweenie**
ZeroMQ is a community-driven high level socket API.  You can use it to build
strange chat services, or large distributed systems using it as a multi-core
concurrency framework.  I'll show you everything you need to start sending
thousands of messages at hundreds of sockets without breaking a sweat.

### CODE REVIEW

**Comment by rkh** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by roidrage** [comment]
+1

**Comment by jumph4x** [comment]
Nice.

**Comment by mrtazz** [comment]
Sounds awesome.

**Comment by constantine-nikolaou** [comment]
:+1:

**Comment by sparrovv** [comment]
+1

**Comment by tchak** [comment]
+1

**Comment by aka47** [comment]
:+1:

**Comment by rkh** [comment]
:-1: - it just became too mainstream, sorry bro‌[⸮](http://en.wikipedia.org/wiki/Irony_punctuation)

**Comment by ghost** [comment]
:+1:

**Comment by johanb** [comment]
:+1:

**Comment by matsimitsu** [comment]
:+1:

**Comment by LevelbossMike** [comment]
:+1:

**Comment by ayosec** [comment]
+1

**Comment by mitch000001** [comment]
+1

**Comment by fritzek** [comment]
+1

**Comment by osegrums** [comment]
+1

**Pull request closed without merging**
