### PR TITLE
Scaling MongoDB for realtime ad analytics

### PR DESCRIPTION
**Pull request by iconara**
You've probably read all the blog posts about how MongoDB is awesome for real time analytics -- but is it? And how do you really do it? I've learnt how to do it the hard way, by making most of the mistakes and trying a few things that turned out to be not so great. You shouldn't have to make those mistakes too. In this talk I'll tell the story of how I built a system that processes tens of millions of ads per day and all the things I did wrong before I got it to work. The things you can't do with MongoDB once you scale up beyond a few hundred operations per second, signs of trouble to look out for and how to dig yourself out when you’re down.

### CODE REVIEW

**Comment by driv3r** [comment]
:+1:

**Comment by moonglum** [comment]
:+1:
Yep, that would be really interesting :)

**Comment by thibaudgg** [comment]
+1

**Comment by yaph** [comment]
:+1:

**Pull request closed without merging**
