### PR TITLE
The Forgotten Test Double - Adam Pohorecki

### PR DESCRIPTION
**Pull request by psyho**
In the recent months our community has adopted a more object-oriented style of writing Rails applications, which has naturally lead us to start using mocks and stubs again.

In these enlightened days we decouple everything and unit test it in isolation, while a small number of end-to-end tests gives us some confidence that the things we test in isolation can actually be combined together and not blow up.

Unfortunately, this approach can not stand the test of time.
Your end-to-end tests will eventually be too slow to run, and you will be left by yourself with a test suite that isolates things so much, that you don't even know if the method you are calling actually exists.

Have you ever encountered a situation where the end-to-end tests fail but all the unit tests pass, or when the end-to-end tests fail to catch all the integration problems?
Have you ever wondered if it is possible to have tests that are both isolated and fast and at the same time give you all confidence that you need to refactor and change your code?

If you have, this talk is for you.
I'm going to show you how to create a fast, reliable test suite, which puts the statically typed languages to shame, using Fakes and Contract Tests.

### CODE REVIEW

**Comment by ku1ik** [comment]
I'm definitely going to enjoy this one, +1

**Comment by DouweM** [comment]
Another +1!

**Comment by tlossen** [comment]
:+1:

**Comment by Stanley** [comment]
:+1:

**Comment by sparrovv** [comment]
:+1:

**Comment by yundt** [comment]
+1

**Comment by mackuba** [comment]
Sounds interesting, it's always hard for me to make tests fast, isolated and readable at the same time, so I'd love to hear some tips on how to achieve that. :+1:

**Comment by knapo** [comment]
:+1:

**Comment by lesniakania** [comment]
+1

**Comment by dmasur** [comment]
+1

**Comment by colszowka** [comment]
+1

**Comment by kurko** [comment]
+2

Contract tests ftw!

**Pull request closed without merging**
