### PR TITLE
You hate your codebase and it's your fault

### PR DESCRIPTION
**Pull request by jonleighton**
# You hate your codebase and it's your fault

Holy crap there are a lot of proposals!
## Talk description in wibbly wobbly attention-grabbing language suitable for, for example, placing on the conference website

Have you ever been frustrated by 'the way it is' in your chosen library or framework? Time to take control!

Jon Leighton will discuss his experimentations creating a different structure for controller code. He will implore you to break free from the shackles of your framework and own it! Like a boss.

[Disclaimer: This talk has avoided the title "How I learned to stop worrying and ..." for the sake of everyone's sanity.]
## A more descriptive description

This is a talk about two things:
1. My experiments in making Rails controller code follow the Single Responsibility Principle and be easier to unit test.
2. More generally, I want to use this as a case study to encourage people to solve their problems themselves rather than waiting/hoping that their framework will come up with a "blessed" way of solving the problem.

I want to give this talk because I want to encourage discussion and feedback about the idea.

FWIW I will also be giving this talk at Railsberry and have proposed it for ScotRuby. So you might not want to hear it again. OTOH the Railsberry slot length will be only 20 minutes and I don't know whether ScotRuby will accept it, so the opportunity to go into a bit more detail would be cool.
## Jon Leighton

Jon Leighton is a Rails core team member, and Technical Director at [Loco2](http://loco2.com/). He lives in London. When he occasionally goes AFK, Jon enjoys dangling from small bits of rock on the sides of cliffs and mountains.

ZOMG
- [My website](http://jonathanleighton.com/)
- [My twitter](https://twitter.com/jonleighton)
- [Past talk video](http://rubymanor.org/3/videos/how_hard_can_it_be_a_refactoring_battle_story/)

### CODE REVIEW

**Comment by DouweM** [comment]
:+1:

**Comment by elisehuard** [comment]
:+1:

**Comment by yundt** [comment]
+1

**Comment by kronn** [comment]
:+1:

**Comment by shingara** [comment]
:+1:

**Comment by sgruhier** [comment]
+1

**Comment by dyba** [comment]
:thumbsup: "He will implore you to break free from the shackles of your framework and own it! Like a boss." Yes! We all need to OWN the framework rather than complain and moan about its shortcomings.

**Comment by jonleighton** [comment]
It's great that people are keen about this. However I've kinda had second thoughts about doing it for EuRuKo - feels like there is too much overlap with the audience with Railsberry...

**Comment by DouweM** [comment]
No! I didn't get to go to Railsberry, and I'd love to hear this talk!

**Comment by b4mboo** [comment]
You are right. Tell us sth. new. Whoever didn't go to Railsberry missed out on sth. great anyways.

**Pull request closed without merging**
