### PR TITLE
Distributed Systems: Tales From the Crypt

### PR DESCRIPTION
**Pull request by ryansmith3136**
A year ago we thought it would be a good idea to start pulling apart services from our core application. Today we have a network of services with clear boundaries, well defined semantics, and concise APIs. The last year was one of the toughest and most enlightening years of my programming life. In this talk I will share the tragedies, heartaches, and victories that we experienced in our migration towards distributed systems. We will look at some patterns and anti-patterns that were discovered along the way. Of course we will be talking about Ruby, PostgreSQL, and their roles in our distributed system.

### CODE REVIEW

**Comment by thijsc** [comment]
Could you undelete the readme?

**Comment by ryansmith3136** [comment]
@thijsc done.

**Comment by tlossen** [comment]
do you really mean "tails" -- or rather "tales", maybe?

**Comment by elisehuard** [comment]
Tim I think that's a pun :)

+1

**Comment by tlossen** [comment]
if that is a pun then i don't get it.

**Comment by ryansmith3136** [comment]
Ha! It is not a pun. Good call.

**Comment by elisehuard** [comment]
I'm disappointed, thought it was a play of words to do with event queues ('tail'-ing) :)
oh well.

**Comment by ryansmith3136** [comment]
@elisehuard Sorry to let you down :( I will definitely be talking about messaging systems though...

**Comment by mackuba** [comment]
I'd love to see that talk, +1.

**Comment by knaveofdiamonds** [comment]
+1

**Pull request closed without merging**
