### PR TITLE
With great power comes great responsibility (was: My proposal)

### PR DESCRIPTION
**Pull request by coffeeaddict**
The talk should be a lecture in favor of defensive, concise, clear minded programming and not against monkey patching; Because monkeys can learn clear mindedness 2 ;-).

BTW: Would include lots off comic book references (and not just uncle Ben)

### CODE REVIEW

**Comment by tlossen** [comment]
hmmm, i think "my proposal" is a bit terse ..... why not put the title and description into your pull request?

**Comment by coffeeaddict** [comment]
but ... but ... i already wrote those once into the readme as specified by the way we should propose... Ow never mind!

**Comment by kronn** [comment]
:+1:

**Comment by coffeeaddict** [comment]
this request has become stale

**Pull request closed without merging**
