### PR TITLE
Rspeccin' #!/bin/bash

### PR DESCRIPTION
**Pull request by ku1ik**

### CODE REVIEW

**Comment by lucek** [comment]
+1, sounds like a good idea. I'd like to hear about that.

**Comment by sparrovv** [comment]
An interesting one, +1

**Comment by tomash** [comment]
+1, bash scripts need automated testing. also bitpocket (=awesome)

**Comment by ml** [comment]
+1

**Comment by pklipp** [comment]
+1

**Comment by yundt** [comment]
+1

**Comment by psyho** [comment]
+1

**Comment by pi3ch** [comment]
+1. was dealing with rsync 2way sync for long time. sounds like bitpocket handles that pretty good.

**Comment by knapo** [comment]
+1

**Comment by lesniakania** [comment]
+1

**Comment by solnic** [comment]
:+1:

**Comment by standin000** [comment]
+1

**Comment by fugo** [comment]
+1 orange_with-it_24

**Pull request closed without merging**
