### PR TITLE
Develop your consciousness by Jorge Dias

### PR DESCRIPTION
**Pull request by diasjorge**
A talk to promote reflection about life and programming

### CODE REVIEW

**Comment by lucaspinto** [comment]
+1

**Comment by yukideluxe** [comment]
+1

**Comment by mediafinger** [comment]
Sounds like a great track for the afternoon, when people start getting tired of too much tech talks (and a tasty lunch)!

**Comment by joahking** [comment]
definitely a +1, coding is a lot about... not only code :-)

**Comment by yaph** [comment]
:+1:

**Pull request closed without merging**
